version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src  
      - ./pom.xml:/app/pom.xml  
      - ~/.m2:/root/.m2  
      - ./static:/app/static
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
